---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: viros-server
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: quay.io/fedora/fedora-coreos
image-version: stable # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      copr:
        - wezfurlong/wezterm-nightly
    install:
      packages:
        - wezterm
        - chezmoi
        - rustup
        - zsh
        - btrfsmaintenance
        - neovim
        - clevis
        - clevis-luks
        - clevis-dracut
        - clevis-udisks2
        - clevis-systemd
        - zoxide
    group-install:
      with-optional: false
      packages:
        - c-development
  - type: signing # this sets up the proper policy & signing files for signed images to work fully
